name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode:
          - "12" # Swift 5.3

    name: "macOS (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install libgit2
        run: brew install libgit2
      - name: Build and Test
        run: swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        swift: ["5.3"]

    name: "Linux (Swift ${{ matrix.swift }})"

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install libgit2
        run: |
          apt-get -qq update
          apt-get install -y libgit2-dev=1.1.0
      - name: Build and Test
        run: swift test --enable-test-discovery
