name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode:
          - "12" # Swift 5.3

    name: "macOS (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-
      - name: Install libgit2
        run: brew install libgit2
      - name: Build and Test
        run: swift test -c release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift: ["5.3"]

    name: "Linux (Swift ${{ matrix.swift }})"

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-swift-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-swift-${{ matrix.swift }}-
      - name: Install libgit2
        run: |
          apt-get -qq update
          apt-get install -y curl unzip cmake libssl-dev libssh2-1-dev python
          curl -L -o libgit2.zip https://github.com/libgit2/libgit2/releases/download/v1.0.1/libgit2-1.0.1.zip
          unzip -q libgit2.zip
          cd libgit2-1.0.1
          ls
          cmake . -DCMAKE_INSTALL_PREFIX=/usr
          cmake --build . --target install
      - name: Build and Test
        run: swift test --enable-test-discovery
